db.venues.insert([{id: "1", name: "Westbury Theatre - sponsored by ATB Financial"},
{id: "2", name: "Backstage Theatre - sponsored by Big Rock Brewery"},
{id: "3", name: "Walterdale Theatre - sponsored by Global Edmonton"},
{id: "4", name: "Academy at King Edward - sponsored by RR Donnelley"},
{id: "5", name: "King Edward School - sponsored by RR Donnelley"},
{id: "6", name: "C103 - sponsored by Nordic"},
{id: "7", name: "Yardbird Suite - sponsored by Chianti Cafe & Restaurant"},
{id: "8", name: "Old Strathcona Performing Arts Centre - Homes by AVI"},
{id: "9", name: "Telus Phone Museum - sponsored by Dyberg Insurance"},
{id: "10", name: "Acacia Hall - sponsored by Dental Choice"},
{id: "11", name: "PCL Studio Theatre"},
{id: "13", name: "Old Strathcona Public Library"},
{id: "14", name: "The Kunitz Shoes Stage at Holy Trinity Anglican Church"},
{id: "15", name: "Cool Air Rentals Stage at Holy Trinity Anglican Church"},
{id: "16", name: "The Sanctuary Stage at Holy Trinity Anglican Church"},
{id: "17", name: "Upstairs at the Armoury"},
{id: "18", name: "Sugar Foot Ballroom"},
{id: "19", name: "DV8 Tavern"},
{id: "20", name: "Wee Book Inn"},
{id: "21", name: "The Billiard Club"},
{id: "22", name: "Old Scona Academic High School"},
{id: "23", name: "Varscona Hotel - Thomas Bennett Room"},
{id: "24", name: "HI-Edmonton Hostel"},
{id: "25", name: "Knox Metropolitan United Church Gym"},
{id: "26", name: "Garneau Theatre"},
{id: "27", name: "Strathcona High School"},
{id: "28", name: "Blues On Whyte"},
{id: "29", name: "Cook County Saloon"},
{id: "30", name: "Princess Theatre"},
{id: "31", name: "Roots on Whyte Conference Room"},
{id: "32", name: "El Cortez Tequila Bar and Kitchen"},
{id: "33", name: "Varscona Parkade"},
{id: "34", name: "Knox Evangelical Free Church"},
{id: "35", name: "La Cite Francophone - l'unitheatre"},
{id: "36", name: "La Cite Francophone - Suzanne Thibaudeau Auditorium"},
{id: "37", name: "Rutherford School"},
{id: "38", name: "Auditorium at Campus Saint-Jean"},
{id: "39", name: "Outdoor Walking Tour"},
{id: "40", name: "CKUA Performance Space"},
{id: "41", name: "Evolution Wonderlounge"},
{id: "42", name: "First Presbyterian Church of Edmonton"},
{id: "43", name: "The Mercury Theater"}]
)